name: JARVIS
description: JARVIS is a framework that manage plugins.
plugins:
  - plugins.simpleBase.Base
  - plugins.simplePrinter.SimplePrinter
  - plugins.monthPrinter.MonthPrinter
  - plugins.simpleModifier.SimpleModifier
  - plugins.modifierPrinter.ModifierPrinter
  - plugins.monitoring.Monitoring